/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
     
    private String name;
    private String color;
    private String brand;
    
    public App(String name,String color,String brand)
    {
    	this.name=name;
    	this.color=color;
    	this.brand=brand;
    }
    
    public String getName(String name)
    {
      return this.name;
    }
    
    public String getColor(String color)
    {
      return this.color;
    }
    
    public String getBrand(String brand)
    {
      return this.brand;
    }
    
    public void call()
    {
    	System.out.print("hello world");
    }
   
    public void printSpecical()
    {
    	System.out.println("name:"+"["+this.getName(brand)+"]"+"color:"+"["+this.getName(color)+"]"+"brand"+"["+this.getName(brand)+"]");
    }
    
}
