/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
     
    private String name;
    private String color;
    private String brand;
    
    public App(String name,String color,String brand)
    {
    	this.name=name;
    	this.color=color;
    	this.brand=brand;
    }
    public void call()
    {
    	System.out.print("hello world");
    }
   
}
