/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        AndroidPhone ad=new AndroidPhone("mobile","blue","vivo");
        ad.call();
    }
}
